name: .NET Tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DISASM_CLIENT_FILES: ""

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    - name: Build client
      run: dotnet publish Disasm.Net.Client/Disasm.Net.Client.csproj --nologo -c release -r linux-x64 -o $DISASM_CLIENT_FILES

    - name: Run tests
      run: dotnet test Disasm.Net.Core.Tests/Disasm.Net.Core.Tests.csproj --nologo --logger "console;verbosity=detailed"
