name: .NET Tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    - name: Run tests
      run: dotnet test Disasm.Net.Core.Tests/Disasm.Net.Core.Tests.csproj --nologo --logger "console;verbosity=detailed"
